# Generated by Django 4.2.4 on 2023-08-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grafxapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_degree', models.FloatField()),
                ('diameter', models.IntegerField()),
                ('clustering_coefficient', models.FloatField()),
            ],
        ),
    ]
