# Generated by Django 4.2.4 on 2023-08-07 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grafxapp', '0002_graphproperties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='centrality',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='node',
            name='degree',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='edge',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_edges', to='grafxapp.node'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_edges', to='grafxapp.node'),
        ),
        migrations.AddField(
            model_name='edge',
            name='graph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grafxapp.graph'),
        ),
        migrations.AddField(
            model_name='graphproperties',
            name='graph',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='grafxapp.graph'),
        ),
        migrations.AddField(
            model_name='node',
            name='graph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grafxapp.graph'),
        ),
    ]
