# Generated by Django 4.2.4 on 2023-08-07 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grafxapp', '0003_graph_node_centrality_node_degree_node_weight_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('name', 'graph')},
        ),
    ]
