# Generated by Django 4.2.4 on 2023-08-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grafxapp', '0005_alter_graphproperties_average_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='branche',
            field=models.CharField(choices=[('UNK', 'Unbekannt'), ('IT', 'Informationstechnologie'), ('FIN', 'Finanzen'), ('HEA', 'Gesundheit'), ('CAR', 'Automobilindustrie'), ('CON', 'Bauwesen'), ('CHE', 'Chemie'), ('EL', 'Elektrizität'), ('LOG', 'Logistik'), ('TOUR', 'Tourismus'), ('AGR', 'Landwirtschaft'), ('EDU', 'Bildung'), ('ENE', 'Energie'), ('FAS', 'Mode'), ('FOO', 'Lebensmittel und Getränke'), ('GOV', 'Regierung und öffentliche Verwaltung'), ('MED', 'Medien'), ('MIN', 'Bergbau'), ('PHAR', 'Pharma'), ('REA', 'Immobilien'), ('RET', 'Einzelhandel'), ('SPOR', 'Sport'), ('TEL', 'Telekommunikation'), ('TRAV', 'Reisen'), ('ENT', 'Unterhaltung')], default='UNK', max_length=4),
        ),
    ]
